version: 0.0
os: windows
files:
  - source: c:\AppFolder
    destination: c:\AppFolder
hooks:
  ApplicationStop :
    - location: stopService.bat
    - location: removeService.bat
  Install :
    - location: installService.bat
      timeout: 180
  ApplicationStart:
    - location: startService.bat
      timeout: 3600
